### ISSUE TITLE
how to install this plugin in Coda 2?

### ISSUE THREAD

**Issue by pengyan518** [sergeche/tea-for-coda#12]
i have downloaded the file:"sergeche-tea-for-coda-8d2966e.zip",when i unzip it , it just a folder, i don't know how to install it.
could you please show me how to install it in Coda 2?

**Comment by sergeche** [comment]
https://github.com/sergeche/zen-coding/downloads

**Comment by pengyan518** [comment]
thanks, i know the url for download, when i download it, it showed me a folder"sergeche-zen-coding-bce28c5",but in the sub-folder, i have not seen the install file, is it in the "plugins"folder?  
i am sorry, this is the first time i install this plugin in coda, could you please tell me how to do it?

**Comment by sergeche** [comment]
You've downloaded a source code zip. I've posted a link with compiled plugins ready to install into editors of choice.

**Comment by pengyan518** [comment]
Thank you so much!
