### ISSUE TITLE
How to install this plugin

### ISSUE THREAD

**Issue by ghost** [sergeche/tea-for-coda#13]
Please, help, I think I got lost how to install this plugin lol. Help please

**Comment by sergeche** [comment]
You should switch to https://github.com/emmetio/Emmet.codaplugin

**Comment by ghost** [comment]
and... how to install it? lol :) I'm just new to Mac.... sorry about dummy question, but please help

**Comment by sergeche** [comment]
Go to https://github.com/emmetio/Emmet.codaplugin and read how to install it.

**Comment by ghost** [comment]
Oops, sorry. And thank you very much Serge!
