### ISSUE TITLE
Lion Support

### ISSUE THREAD

**Issue by mikealmond** [sergeche/tea-for-coda#8]
Is there any plans of adding Lion support to this plugin?

**Comment by sergeche** [comment]
Yes. I'm working on new Zen Coding engine right now and will create a fresh plugin for it  

---

Сергей Чикуёнок
http://chikuyonok.ru
serge.che@gmail.com

**Comment by mikealmond** [comment]
That's great news. Any idea on timeline?

**Comment by sergeche** [comment]
I guess at the end of February.  
BTW, the current version of Coda plugin works fine on my Lion setup. Maybe you installed python3?

---

Сергей Чикуёнок
http://chikuyonok.ru
serge.che@gmail.com (mailto:serge.che@gmail.com)

**Comment by mikealmond** [comment]
I tried to download the latest version here https://github.com/sergeche/tea-for-coda/downloads as well as deleted it form ~/Library/Application Support/Coda/Plugins/

My python version is 2.7.1 http://cl.ly/1U160C1G3y2Y3D1Z071l

**Comment by sergeche** [comment]
Try to download plugin from here: 
https://github.com/sergeche/zen-coding/downloads

**Comment by mikealmond** [comment]
And boom goes the dynamite. Thanks for your help. 

I just sent Panic an email asking them to update the download link on their community plugins page. http://panic.com/coda/developer/community/plugins.php
